### PR TITLE
fix: optional fields are not required and fix stack overflow on extend

### LINKED ISSUE #21: `RangeError: Maximum call stack size exceeded` when using `.extend()` method
The following code is throwing an compile error `RangeError: Maximum call stack size exceeded` 

```ts
class User extends Z.class({
  name: z.string(),
}) {}

class UserAccount extends User.extend({
  email: z.string().email(),
}) {}
```

Here is my `package.json` file with each dependency version

```json
{
  "name": "zod-class-example",
  "version": "0.0.1",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "tsup",
    "dev": "tsup --watch"
  },
  "dependencies": {
    "zod": "^3.22.4",
    "zod-class": "^0.0.12"
  },
  "devDependencies": {
    "@types/node": "^20.11.4",
    "tsup": "^8.0.1",
    "typescript": "^5.3.3"
  }
}
```
I tried to build with `tsup` and `tsc`, both with the same error

### LINKED ISSUE #22: Optional params in schema are required in class creation.
First off great library and it makes some of the worst problems with Zod go away!  Being able to add methods to a validator is fantastic.  The bug / feature that I am running into is there any way to make the optional handlers make the class creation play nice?

```
// Some file.ts in typescript
class drat extends Z.class({
  name: z.string().optional(),
}) {}

const ab = {};
new drat(ab); 

Argument of type '{}' is not assignable to parameter of type '{ name: string; }'.
  Property 'name' is missing in type '{}' but required in type '{ name: string; }'.ts(2345)
```

We can always get around it by just change the params to an any and then letting the validation logic handle anything illegal but it would be nice if optional was optional.

### PR DESCRIPTION
**Pull request by sam-goodwin**
Closes #22 
Closes #21 

Fixes some type errors:
1. Optional properties were still required to be provided
2. TypeScript compiler would stack overflow when calling `extend`

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -25,14 +23,16 @@ import {
...
 } from "zod";
+
 import { toPascalCase } from "./to-pascal-case.js";
-import { isPromise } from "util/types";
+import { isPromise } from "node:util/types";
 
 const IS_ZOD_CLASS = Symbol.for("zod-class");
 
 type Ctor<T = any> = {
+  [key: string]: any;
```
Comment (sam-goodwin) [inline src/index.ts:35]: Oops, i did this for debugging. Can be removed.
